### ISSUE TITLE
MACROs fail to understand EQU

### ISSUE THREAD

**Issue by richardturnnidge** [envenomator/agon-ez80asm#49] opened 2024-02-14 10:35 UTC
If you pass an EQU to a MACRO as an argument, ez80asm assumes the wrong size.
eg, our standard MOSCALL macro...

mos_i2c_open:   EQU  $1F
      MOSCALL mos_i2c_open

Will fail to assemble, stating that the value is too large for a byte.

      MOSCALL $1F
Will work just fine.

**Comment by envenomator** [comment] 2024-02-14 14:57
Hi,
I'm unable to reproduce this. See the output below when I assemble a very small test of MOSCALL:

Assembling test.asm
Pass 1...
Pass 2...
PC     Output            Line Source
040000                   0001     .org $40000
040000                   0002
040000                   0003   macro MOSCALL arg1
040000                   0004   ld a, arg1
040000                   0005   rst.lil $08
040000                   0006   endmacro
040000                   0007
040000                   0008 mos_i2c_open: EQU $1F
040000                   0009
040000                   0010     MOSCALL mos_i2c_open
040000 3E 1F             0010   ld a, arg1
040002 5B CF             0010   rst.lil $08
Done in 0.001 seconds

![image](https://github.com/envenomator/agon-ez80asm/assets/47718809/aabd0652-615e-4900-9161-44ec92ab22b1)
Can you elaborate some more, or send me an example source file?

**Comment by envenomator** [comment] 2024-02-22 15:55
This is fixed in release v1.1

**Closed as completed by envenomator** 2024-02-22 15:55 UTC
