### ISSUE TITLE
macro issue (seen on v1 and 1.2) random - line 1 - Invalid number format (other issues also pointing toward not opening Include files seen)

### ISSUE THREAD

**Issue by tdg8934** [envenomator/agon-ez80asm#62] opened 2024-02-26 17:50 UTC
I was using v1 ez80asm on my asm and it was working well for a while. Last week it started giving me errors when using ez80asm bitmap3.asm and many other variations of asm program code that had include for a macro file (ie. myMacros.inc). I heard there were issues with macros randomly working. Richard Turnnidge and I tried to troubleshoot the issue. I placed on my github site (tdg8934/working) repository from my uSD card. He had no issues with ez80asm bitmap5.asm . I then upgraded to v1.2 and it would still not compile but I saw a different error MACRO [CREATE_BITMAP] - line 1 - invalid number format  .db

I have also tried longer and shorter arguments in my macro included inc. as well copied all to a new formated fat32 uSD card as well as ran on an Agon Light 2 and Console 8 with the same errors. Richard can use the same code and it compiles without issues.

**Comment by richardturnnidge** [comment] 2024-02-26 18:45
With all versions of ez80asm, it assembled on my Mac, v1.0.
On Mac it fails on v1.2.

"Build script for AgonLight2
File: bitmap5.asm 
-----------------------------------------
Assembling bitmap5.asm
Listing to bitmap5.lst
Pass 1...
[31mMACRO [CREATE_BITMAP] - line 1 - Invalid number format
[39m[33m	.db
[39mCreated BIN file: bitmap5.bin "

On emulator, and Agon, it fails on version 1.2.
but works on v0.101, v0.106, v1.0 on Agon and emulator
![420654378_1092778085100755_8099866654384042874_n](https://github.com/envenomator/agon-ez80asm/assets/117299012/297505e0-2d9b-4cb4-abfa-009272d1288c)
![422005691_1129474494710355_5652443260096695814_n](https://github.com/envenomator/agon-ez80asm/assets/117299012/5cc6aa9d-4072-4a69-bea8-9b038825c5bc)
![423063071_234002606467391_7772618073593905476_n](https://github.com/envenomator/agon-ez80asm/assets/117299012/c96eb7c5-b446-4b9b-9a49-3918906edcb4)
![423455122_1063190408100783_4268656223159322704_n](https://github.com/envenomator/agon-ez80asm/assets/117299012/a834ab18-bc54-4121-82b0-078eb455b98d)

**Comment by richardturnnidge** [comment] 2024-02-26 18:58
ISSUE:
If you pass an argument to a MACRO that is a byte, and it expects a byte, it works.
If you pass an argument which is an EQU, it fails. Presumably because an EQU could be any number size?

eg. a macro which passes-
CREATE_BITMAP id, 16, 16, "J0.data" 
where-
id: equ 255
will fail.

But,
CREATE_BITMAP 255, 16, 16, "J0.data" 
will work.

**Comment by envenomator** [comment] 2024-02-26 20:04
I'm using the 'CREATE_BITMAP' from the tdg8934/working repo, and this is the result I get using a named EQU to 255 in the emulator.
![image](https://github.com/envenomator/agon-ez80asm/assets/47718809/97e5b5bc-8455-4d9e-ad95-0d68e3fc6254)
My 'data' file is just 3 bytes, but not really important.

Same on my linux- and windows build. I cannot reproduce this

**Comment by envenomator** [comment] 2024-02-27 11:12
After discussion on facebook with Richard, we determined the actual cause to be EQU statements <following> a .DB statement in an expanded macro. The workaround is defining EQU statements before .DB statements, until the next release

**Comment by envenomator** [comment] 2024-02-27 11:12
Fixed in https://github.com/envenomator/agon-ez80asm/commit/c46f361910819ce3f094d3d468ce465ad3cf6c29

**Comment by envenomator** [comment] 2024-03-01 20:27
Released as v1.3

**Closed as completed by envenomator** 2024-03-01 20:27 UTC
Labels: bug
