### ISSUE TITLE
longer file names causing macro to abort

### ISSUE THREAD

**Issue by richardturnnidge** [envenomator/agon-ez80asm#90] opened 2024-11-13 17:17 UTC
Trying to build an older bit of game code (the mole whacking game), I had an issue with a macro, causing ez80asm to exit with an abort code 6... whatever that is A quick google implied trying to read something out of bounds, but who knows...
No other errors from ez80asm.
It was not an issue when I assembled it at the end of last year, so something has got hurt since then...

This fails:
	DEFBITMAPMOLE 0, "resources/mole64_mound_dithered.data"

Whereas this works:
	DEFBITMAP40 5, "resources/just_mole.data"

The macros being:
	macro DEFBITMAPMOLE arg, file
	.db 23, 27, 0
	.db arg
	.db 23, 27, 1
	.dw 64, 48
	incbin file
	endmacro

	macro DEFBITMAP40 arg, file
	.db 23, 27, 0
	.db arg
	.db 23, 27, 1
	.dw 40, 40
	incbin file
	endmacro

If I write the code out longhand directly in the source without using the macro, it works, ie:
	.db 23, 27, 0
	.db 0 ;arg
	.db 23, 27, 1
	.dw 64, 48
	incbin "resources/mole64_mound_dithered.data" ;file

So, is it length of data? or file name??

I shortened the file name in the argument:
	DEFBITMAPMOLE 0, "resources/mole6d.data"

And that WORKED !!!

So, maybe an issue with file name lengths inside macros?

**Comment by richardturnnidge** [comment] 2024-11-14 15:59
### UPDATE

A file name of 31 chars in length fails to assemble, 30 chars is OK.
If a file is missing, but under 31 chars, there is a sensible file missing error.
If a file is missing but file name length is over 30 chars, then ez80asm aborts with no error.
If a file exists but file name length is over 30 chars, then ez80asm aborts with no error.

This is ONLY when used inside a macro.

Looking at your code (which I am not good at doing...), I see there is a FILENAMEMAXLENGTH set at 64 chars.

My example here is well under that at 36 chars.

However, you also have MAXNAMELENGTH set at 32 for labels.

I wonder if that is being used by mistake somewhere??? or being used differently inside a macro?

I can shorten file names, so can work around, but thought you would want to know as it used to work in 1.4 (I think).

**Comment by envenomator** [comment] 2024-11-20 14:52
Ah, you're running into the defined maximum argument length of 32. While that is documented in the README, I understand how this is confusing when using a filename as a string argument to a macro.
I'll have a look into the 30/31/32 length issue however

**Comment by richardturnnidge** [comment] 2024-11-20 14:57
31 chars probably then adds an extra byte (0?) as termination if it is a c string type??
If a file is in a subfolder, or deeper, file names could easily break 32 limit.

**Comment by envenomator** [comment] 2024-11-20 15:02
The amount of arguments and argument lengths quickly add up to the amount of memory required in the Agon. I'll try to see if matching up the argument length with max filelength can be done without incurring significant extra memory usage.

**Comment by richardturnnidge** [comment] 2024-11-20 15:11
Hmmm, may only ever be an issue then if developing bigger projects, which might well be on a PC/Mac anyway.
I wonder if there is some form of platform build constant which can allow for the extra memory available??

But again, I think this is a rare use case, as we are only having the issue inside macros (I think).

Don't invest too much time into this one!

**Comment by envenomator** [comment] 2024-11-20 15:37
It looks like the only 'static' allocation is in a stack-frame, so even that isn't really static, but temporary during the setup of the macro. The rest of the arguments are stored using malloc in dynamic memory, so no extra overhead in the latter part of memory. So I think this should be an relatively easy fix and make sure the full 64 characters can be used

**Comment by envenomator** [comment] 2024-11-20 16:31
Ahhh. The issue is that I need to verbatimly need to include both double-quotes in the buffer, when expanding the macro. So the actually working filename is 2 less than the maximum. Two solutions to this
1) Actually check the length of the argument, which costs a little more time/performance, but this should have been in anyway
2) We could make the maximum length of the argument two more than the max file name length, to account for the double quotes

**Comment by richardturnnidge** [comment] 2024-11-20 16:52
I just thought that my Mac  'aborting' with no error was not really what your code normally does!!!

...back in the old days, we would call that a 'crash' ;-)

Obviously, I have only tried this on my Mac, not Agon, nor Windows PC, so did worry it might be my build, or an Xcode setting.

**Comment by envenomator** [comment] 2024-11-30 12:07
Released as v1.11

**Closed as completed by envenomator** 2024-11-30 12:07 UTC
Labels: bug
